FROM ubuntu:23.10

RUN mkdir /pimp
ENV PIMP /pimp
ENV TERM xterm-256color
WORKDIR PIMP

COPY pimp .

RUN apt update \
    && apt install -y python3 python3-pip \
    && apt clean

RUN pip install --break-system-packages -r requirements.txt

ENTRYPOINT ["python3", "main.py"]
